# Generated by Django 3.0.10 on 2021-02-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_fix_verbose_name_typo'),
        ('applications', '0017_applicationaggregatedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='active_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Active member'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='age_groups',
            field=models.ManyToManyField(blank=True, related_name='organisations', to='reservations.AgeGroup', verbose_name='Age groups'),
        ),
    ]
