# Generated by Django 3.0.10 on 2021-02-10 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0013_unitgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSectorRoleChoice',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='Verbose name')),
            ],
        ),
        migrations.CreateModel(
            name='UnitRoleChoice',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='Verbose name')),
            ],
        ),
        migrations.CreateModel(
            name='UnitRolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('can_modify_service_sector_roles', 'Can modify service sector roles'), ('can_modify_unit_roles', 'Can modify unit roles'), ('can_manage_units_reservation_units', 'Can create, edit and delete reservation units in certain unit'), ('can_modify_reservation_unit', 'Can modify reservation unit'), ('can_handle_application', 'Can handle application')], max_length=255, verbose_name='Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.UnitRoleChoice', verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='UnitRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('assigner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigner')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.UnitRoleChoice', verbose_name='Role')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spaces.Unit', verbose_name='Unit')),
                ('unit_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spaces.UnitGroup', verbose_name='Unit group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSectorRolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('can_modify_service_sector_roles', 'Can modify service sector roles'), ('can_modify_unit_roles', 'Can modify unit roles'), ('can_manage_units_reservation_units', 'Can create, edit and delete reservation units in certain unit'), ('can_modify_reservation_unit', 'Can modify reservation unit'), ('can_handle_application', 'Can handle application')], max_length=255, verbose_name='Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.ServiceSectorRoleChoice', verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSectorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('assigner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigner')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.ServiceSectorRoleChoice', verbose_name='Role')),
                ('service_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spaces.ServiceSector', verbose_name='Service sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sector_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
